Public Class BotNames
    Public Shared ReadOnly RandomNames As String() = {
    "ShadowBladeX_GGWP", "NoobSlayer69",
    "StellarRage_K.O!", "PwnStar_U",
    "FrostFlame_CarryU_", "SlayAllDay_",
    "N1ghtShad3_GG", "ProGamer_LUL",
    "ThundrHowl_RankKing", "AFK_Noob",
    "CrimsonR7_JungleBoss", "FeedMe_U",
    "DragonSoul_BreakDef_", "EzWin_",
    "GloomStalk_666_LUL", "GG_EZ",
    "InfernoMage_Init!ate", "N1ceTry",
    "FrostHeart_Carried_", "LagSpike",
    "StormShooterDPS", "NoScope_",
    "AbyssWalk_Survive_", "GG_WP",
    "Moonlit_SoloKill!", "Smurf_",
    "DawnBlade_Counter_", "Tilted_",
    "ShadowX9_TowrSteal", "Lagging",
    "ThunderChant_Penta!", "NoobTube",
    "CelestialR_StarB", "Pro_Move",
    "CrimsonD_ACE_", "EZClap",
    "FrostfireJ_Legend!", "Camping",
    "DragonShdw_Massacre_", "Griefing",
    "NetherPhan_Blink_", "LagSwitch",
    "CelestWrath_Godlike!", "NoobTeam",
    "IceBladeD_Freeze_", "Pro_Play",
    "GaleWings_Harvest_", "RageQuit",
    "AbyssHunt_Bush_", "CampSpot",
    "LunarJudge_Finisher_", "NoobSkill",
    "DawnVang_1stBlood", "Pro_Strat",
    "NoctLoner_Invis_", "Lagfest",
    "ThunderF_Nuke!", "NoobTube_",
    "StellarDr_Flash_", "EZPZ",
    "CrimSunset_1HP_", "Pro_Gamer",
    "FrostDance_Combo!", "Noob_",
    "DragonAw_Ult_", "Pro_Tip",
    "NetherSong_CC_", "LaggingOut",
    "InfernoS_AreaDmg", "Noob_AFK",
    "IceHunt_Slow_", "Pro_Build",
    "StormHrt_Comeback_", "Noob_Feed",
    "JungleLurker_", "Pro_Carry",
    "FountainCmdr_", "LagMachine",
    "FlashIntoWall_", "Noob_Ult",
    "MissUltiKing_", "Pro_Killer",
    "ACE_Engine_", "Noob_Lag",
    "1HP_Escape_", "Pro_Win",
    "DragonStealer_", "Noob_Fail",
    "ReverseQ_", "Pro_Skill",
    "AFK_Fountain_", "Noob_Troll",
    "Feeder_", "Pro_Team",
    "BaseRusher_", "LagSpike_",
    "FlashToGrave_", "Noob_Die",
    "FountainGod_", "Pro_God",
    "MissUltiArt_", "Noob_Cry",
    "ACE_Engine2_", "Pro_Legend",
    "1HP_Counter_", "Noob_Rage",
    "BuffStealer_", "Pro_Slay",
    "ReverseR_", "Noob_Quit",
    "AFK_Now_", "FrostByteX", "L33tGamer99", "XiaoYun_7", "VoidWalker", "QwErTyZ", "Phoenix2077", "Snake_Eyes", "WangFei_123", "NeonNinja",
    "R4nd0mGuy", "StarDust", "LiHua_Pro", "ShadowMage", "T4c0_Cat", "AuroraBore", "ZhangWei_X", "CyberWolf", "K9fG7mX", "MoonSlayer", "ChenLin_2",
    "Dr4g0nFly", "SteelPhoenix", "WuKong_21", "P4r4d0x", "EclipseX", "LiuYang_8", "ThunderBot", "Xy9tLp", "FireLord", "MeiLing_9", "Z3r0Cool", "SkyShark",
    "HeXaG0n", "JadeDragon", "B1oH4zard", "NightFury", "SuLing_5", "Gl1tch3d", "WarPenguin", "D4rkKn1ght", "CloudStrife", "ZhaoJun_3", "NanoSoldier", "V0idCore",
    "LingFei_1", "SparkBlade", "M3t4lGear", "DragonTamer", "TianYu_6", "S0ulReaper"
}
    Public Shared ReadOnly Property PickOne As String
        Get
            Return Pick(RandomNames)
        End Get
    End Property
End Class
